export const MAIN_IMAGE_FETCH_LOADING = "MAIN_IMAGE_FETCH_LOADING";
export const MAIN_IMAGE_FETCH_SUCCESS = "MAIN_IMAGE_FETCH_SUCCESS";
export const MAIN_IMAGE_FETCH_FAILED = "MAIN_IMAGE_FETCH_FAILED";
export const MAIN_IMAGE_REMOVE = "MAIN_IMAGE_REMOVE";

export const APPROVED_IMAGES_ADD_IMAGE = "APPROVED_IMAGES_ADD_IMAGE";
export const APPROVED_IMAGES_REMOVE_IMAGE = "APPROVED_IMAGES_REMOVE_IMAGE";

export const REJECTED_IMAGES_ADD_IMAGE = "REJECTED_IMAGES_ADD_IMAGE";